apiVersion: v1
kind: Service
metadata:
  name: nginx-init-svc
  namespace: netology
spec:
  type: NodePort
  selector:
    app: nginx-init
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30515
